"""Solveit basic helpers"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['setup_dialog', 'solveit_version', 'in_dialog', 'get_caller_globals', 'at_', 'get_tool_names', 'add_tools_card',
           'setup_ns', 'get_output', 'info', 'add_info', 'summarize']

# %% ../nbs/00_core.ipynb 3
import re
import sys
import inspect
from typing import Any
from fastcore.xtras import is_listy
import dialoghelper
from dialoghelper.core import _find_frame_dict, add_msg, mk_toollist, find_msg_id, is_usable_tool, read_msg
from dialoghelper.inspecttools import resolve

# %% ../nbs/00_core.ipynb 19
def solveit_version():
    "Return the version of solveit if it is found"
    s = ' '.join(_.__module__ for _ in sys.meta_path)
    mtch = re.match(r'.*__editable___solveit_(\d+)_(\d+)_(\d+)_finder', s)
    return f"{mtch[1]}.{mtch[2]}.{mtch[3]}" if mtch else ''

# %% ../nbs/00_core.ipynb 21
def in_dialog():
    "Check if the code is running in a solveit dialog"
    return bool(solveit_version() and dialoghelper.find_dname() and dialoghelper.find_msg_id())

# %% ../nbs/00_core.ipynb 23
def get_caller_globals(): 
    "Return the globals of the caller"
    return inspect.currentframe().f_back.f_globals

# %% ../nbs/00_core.ipynb 30
_empty = inspect.Parameter.empty

# %% ../nbs/00_core.ipynb 40
def at_(
    o, # Object to traverse (dict, list, object, or nested combination)
    sym: str, # Path using dots and/or brackets (e.g., 'a.b[0].c' or 'a[b][c]')",
    default: Any=_empty, # Value to return if path not found (raises exception if not provided)
    sep='.' # Separator for path segments
) -> Any: # Value at the specified path
    "Traverse nested `o` using path `sym` with dot notation and/or bracket indexing"
    sym = re.sub(r'\[([^\]]+)\]', r'.\1', sym)
    try:
        for a in filter(None, sym.split(sep)):
            if a.lstrip('-').isdigit(): a = int(a)
            try: o = o[a]
            except Exception:
                if isinstance(a, int):
                    try: o = o[str(a)]; continue
                    except Exception: pass
                o = getattr(o, a)
    except Exception:
        if default is not _empty: return default
        raise
    return o

# %% ../nbs/00_core.ipynb 69
def get_tool_names(ns=None, exclude=None, only_exported=False, exclude_private=True):
    "Return the names of all tools in namespace `ns` or current dialog."
    ns = ns or _find_frame_dict('__msg_id')
    exports = set(getattr(ns, '__all__', []))
    if exclude: exclude = set(get_tool_names(exclude) if not is_listy(exclude) else exclude)
    if inspect.ismodule(ns): ns = vars(ns)
    for k,v in ns.items():
        if exclude_private and k[0] == '_': continue
        if only_exported and k not in exports: continue
        if exclude and k in exclude: continue
        if not hasattr(__builtins__, k) and callable(v):
            try: 
                if is_usable_tool(v): yield k
            except Exception: pass

# %% ../nbs/00_core.ipynb 74
def add_tools_card(ns=None):
    "Add a message with all tools in namespace `ns` or caller globals"
    ns = ns or _find_frame_dict('__msg_id')
    add_msg(mk_toollist(ns[_] for _ in get_tool_names(ns)))

# %% ../nbs/00_core.ipynb 78
def setup_ns(ns=None, **kwargs):
    "Add `kwargs` to the namespace `ns` or current dialog"
    ns = ns or _find_frame_dict('__msg_id')
    # lc = list(locals().items())[1:]
    thisid = find_msg_id()
    for k,v in kwargs.items(): ns[k] = v
    msgid = add_msg('\n\n'.join(f"{k} = {v}" for k,v in kwargs.items()))
    print(thisid, msgid)

setup_dialog = setup_ns

# %% ../nbs/00_core.ipynb 86
def get_output(msgid:str=None) -> list[str]:
    read_msg(n=0, relative=True, msgid=msgid or find_msg_id())
    if output := resolve('msg.output'):
        if isinstance(output, str): return output  # prompt
    if isinstance(o, str): return [o]

# %% ../nbs/00_core.ipynb 88
def info():
    "Returns information about the dialog"
    s = f'''
Solveit version: {solveit_version()}  
dialoghelper version: {dialoghelper.__version__}  
'''
    return s

# %% ../nbs/00_core.ipynb 90
def add_info(msgid:str=''):
    "Add a message with information about the dialog"
    return add_msg(info(), id=msgid)

# %% ../nbs/00_core.ipynb 96
def summarize(target, context): pass
