# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_flakes.ipynb.

# %% auto 0
__all__ = ['ListReporter', 'check_flakes', 'add_flakes', 'show_flakes']

# %% ../nbs/05_flakes.ipynb
import re
from collections import defaultdict
from IPython.display import Markdown
from itertools import repeat
from pathlib import Path
from urllib.parse import quote_plus
import fastcore.all as FC
import pyflakes
from pyflakes.reporter import Reporter
from pyflakes.messages import Message
from pyflakes.api import check as _check
from dialoghelper.core import find_msgs, find_dname, find_msg_id, find_var, read_msg, update_msg, add_msg

# %% ../nbs/05_flakes.ipynb
@FC.patch
def as_tuple(self: Message): return type(self).__name__, self.filename, (self.lineno, self.col+1), self.message %self.message_args, self.message_args

# %% ../nbs/05_flakes.ipynb
class ListReporter(Reporter):
    def __init__(self): self.warnings = FC.L(); super().__init__(None, None)
    def flake(self, message): self.warnings.append(message.as_tuple())

# %% ../nbs/05_flakes.ipynb
def check_flakes(
    src:str=None,
    srcname:str=None, 
):
    "Check for pyflakes 'warnings' in `src` or current dialog"
    if not src:
        cds = find_msgs(msg_type='code')
        src = '\n'.join(cds.filter(lambda x: x.is_exported).itemgot('content'))
        if not srcname and nbdev.config.is_nbdev():
            if s := FC.first(m.content for m in cds if m.content and re.match(r'\s*#\s*\|', m.content.split()[0])):
                dirct = (s.strip()[2:]).strip().split()
                if dirct[0] == 'default_exp' and len(dirct) > 1: srcname = f"{dirct[1]}.py"
    if not srcname:
        srcname = (Path.home()/find_dname()).with_suffix('.py').name
    _check(src, srcname, reprt := ListReporter())
    return reprt.warnings
    

# %% ../nbs/05_flakes.ipynb
def _line2msgid(codes, msgids):
    line, l2id = 1, FC.L()
    for code, msgid in zip(codes, msgids):
        code = f"# %% msgid: {msgid}\n{code}\n".split('\n')
        end = line + code.count('\n') + 2
        l2id.extend(zip(code, range(0, len(code)-1), repeat(msgid)))
        line = end
    return l2id

# %% ../nbs/05_flakes.ipynb
def _get_source(msgs):
    l2id = _line2msgid(msgs.attrgot('content'), msgs.attrgot('id'))
    return '\n'.join(l2id.itemgot(0)), l2id

# %% ../nbs/05_flakes.ipynb
def _warningtypes():
    "Return all pyflakes message types"
    pfmod = pyflakes.messages
    kls_msg = pfmod.Message
    syms = [_ for _ in dir(pfmod) if _[0] != '_']
    return {sym: o.__doc__.strip() if o.__doc__ else o.message
        for sym in syms 
        if sym != 'Message' and isinstance(o := getattr(pfmod, sym), type) and kls_msg in o.mro()}

# %% ../nbs/05_flakes.ipynb
_ALL = ','.join(_warningtypes().keys())
_IMPORTS = 'ImportShadowedByLoopVar,ImportStarNotPermitted,ImportStarUsage,ImportStarUsed,LateFutureImport,UnusedImport'
_VARS = 'UndefinedExport,UndefinedLocal,UndefinedName,UnusedIndirectAssignment,UnusedVariable'


# %% ../nbs/05_flakes.ipynb
def check_flakes(dname:str='', wtypes:str=_ALL):
    "Check for pyflakes 'warnings' in `sname` or current dialog"
    cds = find_msgs(msg_type='code', dname=dname)
    src, l2id = _get_source(cds.filter(lambda x: x.is_exported))
    nw = _check(src, Path(dname or find_dname()).name, reprt := ListReporter())
    if wtypes != _ALL: wtypes = wtypes.split(',')
    return nw, l2id, reprt.warnings if wtypes == _ALL else reprt.warnings.filter(lambda x: x[0] in wtypes)

# %% ../nbs/05_flakes.ipynb
def _group_flakes(wns, l2id):
    "Group pyflakes warnings by msgid and warning type"
    res = defaultdict(lambda:defaultdict(list))
    for wtype, _, rng, *rest in wns:
        msgid = l2id[rng[0]-1][2]
        res[msgid][wtype].append((rng, rest))
    return res

# %% ../nbs/05_flakes.ipynb
def _tag(name, msgid=''): return f"<!-- {name}: {msgid or find_msg_id()} -->"

# %% ../nbs/05_flakes.ipynb
_lnks = (
    '''<span hx-on-click="setTimeout(() => selectMsg($('%s'), {centered: true}), 100)" class="uk-link text-blue-600 p-1 cursor-pointer hover:bg-muted truncate">**%s**</span>  \n\n''',
    '''<h5 class="uk-flex"><a class="uk-link" href="%s"><strong>%s</strong></svg></a>&nbsp;<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" height="16px" width="16px" class="lucide-icon "><use href="#lc-external-link"></use></h5>  \n\n'''
)

# %% ../nbs/05_flakes.ipynb
def _render_flakes_report(dname, wns, l2id):
    tag = _tag('flakes report')
    dlnk, s = '', f"{tag}\n"
    if dname:
        q = quote_plus((str(Path(find_dname()).parent/dname) if not dname or dname[0]!='/' else dname)[1:])
        dlnk = f"/dialog_?name={q}"
    grouped = _group_flakes(wns, l2id)
    for msgid, wtypes in grouped.items():
        lnk = f"{dlnk}#{msgid}"
        s += _lnks[bool(dname)] % (lnk, msgid)
        for wtype, ws in wtypes.items():
            s += f"- **{wtype}**: {len(ws)}  \n"
            for w in ws: s += f"    `{w[0]}`: {w[1][0].replace("'", "`")}  \n"
        s += '\n'
    return s, tag

# %% ../nbs/05_flakes.ipynb
get_ipython().xpush(__linked_msgs={})  # WARNING: neither get_ipython (in user_ns) nor ipykernel_helper.xpush are documented

# %% ../nbs/05_flakes.ipynb
def _update_linked_msg(content, tag, msgid=''):
    msgid = msgid or find_msg_id()
    linked = find_var('__linked_msgs')
    if reportid := linked.get(msgid):
        msg = read_msg(0, True, reportid, nums=True)
        if 'msg' not in msg and re.search(tag, msg.content):
            linked[msgid] = update_msg(reportid, content=content)
            return
    linked[msgid] = add_msg(content)

# %% ../nbs/05_flakes.ipynb
def add_flakes(
    dname:str='',  # Dialog to check; defaults to current dialog
    wtypes:str=_ALL # comma separated list of warning types to include; defaults to all
):
    """Add a message below with the warnings generated by pyflakes.
If `dname` is None, the current dialog is used. Dialog names other than None must be paths relative to the solveit root directory (if starting with `/`) or relative to the current dialog (if not starting with `/`), and should *not* include the .ipynb extension."""
    n, l2id, wns = check_flakes(dname, wtypes)
    s, tag = _render_flakes_report(dname, wns, l2id)
    _update_linked_msg(s, tag)

def show_flakes(
    dname:str='',  # Dialog to check; defaults to current dialog
    wtypes:str=_ALL # comma separated list of warning types to include; defaults to all
):
    """Show the warnings generated by pyflakes.
If `dname` is None, the current dialog is used. Dialog names other than None must be paths relative to the solveit root directory (if starting with `/`) or relative to the current dialog (if not starting with `/`), and should *not* include the .ipynb extension."""
    n, l2id, wns = check_flakes(dname, wtypes)
    s, tag = _render_flakes_report(dname, wns, l2id)
    display(Markdown(s))
