# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_flakes.ipynb.

# %% auto 0
__all__ = ['IMPORTS', 'VARS', 'ListReporter', 'get_tagged_source', 'check_source_flakes', 'check_flakes', 'add_flakes',
           'show_flakes']

# %% ../nbs/05_flakes.ipynb
from collections import defaultdict
from IPython.display import Markdown
from itertools import repeat
from pathlib import Path
from urllib.parse import quote_plus
import fastcore.all as FC
import pyflakes
from pyflakes.reporter import Reporter
from pyflakes.messages import Message
from pyflakes.api import check as _check
from dialoghelper.core import find_msgs, find_dname
from .core import link_msg

# %% ../nbs/05_flakes.ipynb
@FC.patch
def as_tuple(self: Message): return type(self).__name__, self.filename, (self.lineno, self.col+1), self.message %self.message_args, self.message_args

# %% ../nbs/05_flakes.ipynb
class ListReporter(Reporter):
    def __init__(self): self.warnings = FC.L(); super().__init__(None, None)
    def flake(self, message): self.warnings.append(message.as_tuple())

# %% ../nbs/05_flakes.ipynb
def _line2msgid(codes, msgids):
    "Return list of (code_line, line_num_in_msg, msgid) tuples for each concatenated source line"
    line, l2id = 1, FC.L()
    for code, msgid in zip(codes, msgids):
        codelns = f"# %% msgid: {msgid}\n{code}\n".split('\n')
        l2id.extend(zip(codelns, range(0, len(codelns)-1), repeat(msgid)))
        line += len(codelns)
    return l2id

# %% ../nbs/05_flakes.ipynb
def get_tagged_source(
    msgs:list  # List of message dicts with 'content' and 'id' keys
) -> tuple[str, list]:  # Returns (source, line_mapping) where line_mapping maps each source line to (code_line, line_in_msg, msgid)
    "Concatenate message contents with msgid markers"
    l2id = _line2msgid(msgs.attrgot('content'), msgs.attrgot('id'))
    return '\n'.join(l2id.itemgot(0)), l2id

# %% ../nbs/05_flakes.ipynb
def _warningtypes():
    "Return all pyflakes message types"
    pfmod = pyflakes.messages
    kls_msg = pfmod.Message
    syms = [_ for _ in dir(pfmod) if _[0] != '_']
    return {sym: o.__doc__.strip() if o.__doc__ else o.message
        for sym in syms 
        if sym != 'Message' and isinstance(o := getattr(pfmod, sym), type) and kls_msg in o.mro()}

# %% ../nbs/05_flakes.ipynb
_ALL = ','.join(_warningtypes().keys())
IMPORTS = 'ImportShadowedByLoopVar,ImportStarNotPermitted,ImportStarUsage,ImportStarUsed,LateFutureImport,UnusedImport'
VARS = 'UndefinedExport,UndefinedLocal,UndefinedName,UnusedIndirectAssignment,UnusedVariable'


# %% ../nbs/05_flakes.ipynb
def check_source_flakes(
    src:str,  # source code, typically concatenated exported code cells
    src_name:str='',  # name of source (needed by pyflakes)
) -> list:  # Returns list of (type, name, (line,col), msg, args) tuples
    "Check for pyflakes 'warnings' in `src`"
    _check(src, src_name or 'synthetic', reprt := ListReporter())
    return reprt.warnings

# %% ../nbs/05_flakes.ipynb
def _get_flakes(dname='', wtypes=''):
    cds = find_msgs(msg_type='code', dname=dname)
    src, l2id = get_tagged_source(cds.filter(lambda x: x.is_exported))
    ws = check_source_flakes(src, Path(dname or find_dname()).name)
    if wtypes: 
        ts = set(FC.L(wtypes.split(',')).map(str.strip))
        ws = ws.filter(lambda w: w[0] in ts)
    return l2id, ws

def check_flakes(
    dname:str='',  # dialog name (relative like 'data/test' or absolute), defaults to current
    wtypes:str=''  # filter: IMPORTS, VARS, or comma-separated warning types like 'UnusedImport,UndefinedName'; defaults to all types
) -> list:  # [{'wtype':'UnusedImport', 'description':"'os' imported but unused", 'id':'_abc123', 'line_n':5}, ...]
    "Check exported code for pyflakes issues"
    l2id, ws = _get_flakes(dname, wtypes)
    return [dict(wtype=w[0], description=w[3], id=l2id[w[2][0]-1][2], line_n=l2id[w[2][0]-1][1]) for w in ws]

# %% ../nbs/05_flakes.ipynb
def _group_flakes(ws, l2id):
    "Group pyflakes warnings by message id and warning type"
    res = defaultdict(lambda:defaultdict(list))
    for wtype, _, rng, *rest in ws:
        msgid = l2id[rng[0]-1][2]
        res[msgid][wtype].append((rng, rest))
    return res

# %% ../nbs/05_flakes.ipynb
_lnks = (
    '''<span hx-on-click="setTimeout(() => selectMsg($('%s'), {centered: true}), 100)" class="uk-link text-blue-600 p-1 cursor-pointer hover:bg-muted truncate">**%s**</span>  \n\n''',
    '''<h5 class="uk-flex"><a class="uk-link" href="%s"><strong>%s</strong></svg></a>&nbsp;<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" height="16px" width="16px" class="lucide-icon "><use href="#lc-external-link"></use></h5>  \n\n'''
)

# %% ../nbs/05_flakes.ipynb
def _render_flakes_report(dname, ws, l2id):
    dlnk, s = '', ''
    if dname:
        q = quote_plus((str(Path(find_dname()).parent/dname) if not dname or dname[0]!='/' else dname)[1:])
        dlnk = f"/dialog_?name={q}"
    grouped = _group_flakes(ws, l2id)
    for msgid, wtypes in grouped.items():
        lnk = f"{dlnk}#{msgid}"
        s += _lnks[bool(dname)] % (lnk, msgid)
        for wtype, ws in wtypes.items():
            s += f"- **{wtype}**: {len(ws)}  \n"
            for w in ws: s += f"    `{w[0]}`: {w[1][0].replace("'", "`")}  \n"
        s += '\n'
    return s

# %% ../nbs/05_flakes.ipynb
def add_flakes(
    dname:str='',  # dialog name (relative like 'data/test' or absolute), defaults to current
    wtypes:str='' # filter: IMPORTS, VARS, or comma-separated warning types like 'UnusedImport,UndefinedName'; defaults to all types
):
    """Add a message with the warnings generated by pyflakes on the exported code.

Dialog names other than the default must be paths relative to the solveit root directory (if starting with `/`) or relative to the current dialog (if not starting with `/`), and should *not* include the .ipynb extension."""
    l2id, ws = _get_flakes(dname, wtypes)
    s = _render_flakes_report(dname, ws, l2id)
    link_msg(s)

def show_flakes(
    dname:str='',  # dialog name (relative like 'data/test' or absolute), defaults to current
    wtypes:str='' # filter: IMPORTS, VARS, or comma-separated warning types like 'UnusedImport,UndefinedName'; defaults to all types
):
    """Show the warnings generated by pyflakes on the exported code.

Dialog names other than the default must be paths relative to the solveit root directory (if starting with `/`) or relative to the current dialog (if not starting with `/`), and should *not* include the .ipynb extension."""
    l2id, ws = _get_flakes(dname, wtypes)
    s = _render_flakes_report(dname, ws, l2id)
    display(Markdown(s if s else 'No warnings to report'))
