"""fastgit patches and git utils"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_git.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/07_git.ipynb #e72f67fd
import fastcore.all as FC
from fastgit import Git

# %% ../nbs/07_git.ipynb #69d2773e
_c_cmds = {'diff', 'log', 'status', 'show', 'blame', 'branch', 'reflog'}
_c_alias = {'cdiff', 'clog', 'cstatus', 'cshow', 'cblame', 'cbranch', 'creflog'}
_diffc = {'+': '\033[32m', '-': '\033[31m', '@': '\033[36m'}

def _cdiff(lines, nlines=100):
    for ln in lines[:nlines]: print(f"{_diffc.get(ln[0] if ln else '', '')}{ln}\033[0m")

def _cstatus(lines, nlines=100):
    for ln in lines[:nlines]:
        c = '\033[32m' if ln.startswith('\t') and 'new file' in ln else '\033[31m' if ln.startswith('\tmodified') or ln.startswith('\tdeleted') else '\033[36m' if ln.startswith('\t') else ''
        print(f"{c}{ln}\033[0m")

def _clog(lines, nlines=100):
    for ln in lines[:nlines]:
        c = '\033[33m' if ln.startswith('commit ') else '\033[32m' if ln.startswith('Author:') else '\033[36m' if ln.startswith('Date:') else ''
        print(f"{c}{ln}\033[0m")

def _creflog(lines, nlines=100):
    for ln in lines[:nlines]:
        parts = ln.split(' ', 1)
        print(f"\033[33m{parts[0]}\033[0m {parts[1] if len(parts)>1 else ''}")

_colorizers = dict(diff=_cdiff, show=_cdiff, status=_cstatus, log=_clog, blame=_clog, branch=_cstatus, reflog=_creflog)

# %% ../nbs/07_git.ipynb #8cfc708e
@FC.patch_to(Git, nm='__getattr__')
def _getattr(self, nm):
    if nm.startswith('_'): raise AttributeError(nm)
    is_c = nm in _c_alias
    if is_c: nm = nm[1:]
    cmd = nm.replace('_', '-')
    def _run(*args, color=None, nlines=100, **kwargs):
        res = self(cmd, *args, **kwargs)
        if res and (color or is_c): _colorizers.get(cmd, _cdiff)(res if isinstance(res, list) else res.splitlines(), nlines=nlines)
        else: return res
    return _run
