"""Using `htmx` javascript API from python"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_htmx_bridge.ipynb.

# %% auto #0
__all__ = ['js_bridge', 'setup_htmx_bridge', 'swap', 'find', 'findAll', 'closest', 'remove', 'addClass', 'removeClass',
           'toggleClass', 'takeClass', 'trigger', 'process', 'values', 'parseInterval', 'logAll', 'logNone', 'ajax']

# %% ../nbs/00_htmx_bridge.ipynb #f3fbd0a5
import asyncio
from uuid import uuid4
from fastcore.meta import delegates
from fastcore.xml import to_xml
from starlette.routing import Route
from starlette.responses import HTMLResponse
from fasthtml.common import fast_app
from fasthtml.jupyter import JupyUvi, is_port_free
from dialoghelper.core import iife_a, event_get_a

# %% ../nbs/00_htmx_bridge.ipynb #815fcf49
async def setup_htmx_bridge(debugger:bool=False):
    "Inject htmx bridge JS shim into the browser"
    await iife_a(f"{'debugger;\n' if debugger else ''}"+js_bridge)

# %% ../nbs/00_htmx_bridge.ipynb #06808779
async def _htmx_call(method, *args, port=8000, full_response=False, timeout=30):
    "Low-level async call to htmx JS API"
    return await event_get_a('htmx_bridge', timeout=timeout, data=dict(method=method, args=args, port=port, full_response=full_response))

# %% ../nbs/00_htmx_bridge.ipynb #64ecf130
@delegates(_htmx_call)
def swap(target, content, swapSpec=None, swapOptions=None, **kwargs):
    "Perform an htmx swap, blocking until complete"
    if not isinstance(content, str): content = to_xml(content)
    return _htmx_call('swap', target, content, swapSpec or dict(swapStyle='innerHTML'), swapOptions or {}, **kwargs)

# %% ../nbs/00_htmx_bridge.ipynb #e8a23e77
#| linkedto: _d0ffe3e2
js_bridge = '''
(function() {
    const _xhr_fields = ['status', 'statusText', 'responseText', 'responseURL'];
    const _serialize_xhr = xhr => Object.fromEntries(_xhr_fields.map(k => [k, xhr[k]]));
    const _serialize_detail = d => ({
        ...(d.xhr ? {xhr: _serialize_xhr(d.xhr)} : {}),
        successful: d.successful, failed: d.failed,
        pathInfo: d.pathInfo ? {requestPath: d.pathInfo.requestPath, finalRequestPath: d.pathInfo.finalRequestPath} : undefined
    });

    const _handlers = {
        ajax: ({idx, args, full_response}) => {
            let [verb, path, context] = args;
            const handler = e => {
                const res = {success: {swapped: true}};
                if (full_response) res.response = _serialize_detail(e.detail);
                pushData(idx, res);
            };
            htmx.on('htmx:afterRequest', handler);
            htmx.ajax(verb, path, context ?? {})
                .catch(err => pushData(idx, {error: String(err)}))
                .finally(() => htmx.off('htmx:afterRequest', handler));
        },
        swap: ({idx, args, full_response}) => {
            try {
                const [target, content, swapSpec, swapOptions] = args;
                htmx.swap(target, content, swapSpec ?? {swapStyle: 'innerHTML'}, swapOptions ?? {});
                const res = {success: {swapped: true}};
                if (full_response) res.response = null;
                pushData(idx, res);
            } catch(e) { pushData(idx, {error: String(e)}); }
        },
        remove:       ({idx, args}) => { try { htmx.remove(htmx.find(args[0]), args[1] ?? undefined); pushData(idx, {success: {}}); } catch(e) { pushData(idx, {error: String(e)}); } },
        addClass:     ({idx, args}) => { try { htmx.addClass(htmx.find(args[0]), args[1], args[2] ?? undefined); pushData(idx, {success: {}}); } catch(e) { pushData(idx, {error: String(e)}); } },
        removeClass:  ({idx, args}) => { try { htmx.removeClass(htmx.find(args[0]), args[1], args[2] ?? undefined); pushData(idx, {success: {}}); } catch(e) { pushData(idx, {error: String(e)}); } },
        toggleClass:  ({idx, args}) => { try { htmx.toggleClass(htmx.find(args[0]), args[1]); pushData(idx, {success: {}}); } catch(e) { pushData(idx, {error: String(e)}); } },
        takeClass:    ({idx, args}) => { try { htmx.takeClass(htmx.find(args[0]), args[1]); pushData(idx, {success: {}}); } catch(e) { pushData(idx, {error: String(e)}); } },
        trigger:      ({idx, args}) => { try { htmx.trigger(htmx.find(args[0]), args[1], args[2] ?? {}); pushData(idx, {success: {}}); } catch(e) { pushData(idx, {error: String(e)}); } },
        process:      ({idx, args}) => { try { htmx.process(htmx.find(args[0])); pushData(idx, {success: {}}); } catch(e) { pushData(idx, {error: String(e)}); } },
        values:       ({idx, args}) => { try { pushData(idx, {success: {result: htmx.values(htmx.find(args[0]), args[1])}}); } catch(e) { pushData(idx, {error: String(e)}); } },
        parseInterval:({idx, args}) => { try { pushData(idx, {success: {result: htmx.parseInterval(args[0])}}); } catch(e) { pushData(idx, {error: String(e)}); } },
        logAll:       ({idx})       => { try { htmx.logAll(); pushData(idx, {success: {}}); } catch(e) { pushData(idx, {error: String(e)}); } },
        logNone:      ({idx})       => { try { htmx.logNone(); pushData(idx, {success: {}}); } catch(e) { pushData(idx, {error: String(e)}); } },
        find:         ({idx, args}) => { try { const e = htmx.find(args[0]); if (!e) return pushData(idx, {error: `No element found: ${args[0]}`}); pushData(idx, {success: {id: e.id, tagName: e.tagName.toLowerCase(), outerHTML: e.outerHTML}}); } catch(e) { pushData(idx, {error: String(e)}); } },
        findAll:      ({idx, args}) => { try { const els = [...htmx.findAll(args[0])]; pushData(idx, {success: {count: els.length, items: els.map(e => ({id: e.id, tagName: e.tagName.toLowerCase(), outerHTML: e.outerHTML}))}}); } catch(e) { pushData(idx, {error: String(e)}); } },
        closest:      ({idx, args}) => { try { const e = htmx.closest(htmx.find(args[0]), args[1]); if (!e) return pushData(idx, {error: `No ancestor found: ${args[1]}`}); pushData(idx, {success: {id: e.id, tagName: e.tagName.toLowerCase(), outerHTML: e.outerHTML}}); } catch(e) { pushData(idx, {error: String(e)}); } },
    };

    if (window._htmx_bridge_handler) document.body.removeEventListener('htmx_bridge', window._htmx_bridge_handler);
    window._htmx_bridge_handler = e => {
        const payload = e.detail;
        const handler = _handlers[payload.method];
        if (!handler) return pushData(payload.idx, {error: `Unknown method: ${payload.method}`});
        handler(payload);
    };
    document.body.addEventListener('htmx_bridge', window._htmx_bridge_handler);
})();
'''

# %% ../nbs/00_htmx_bridge.ipynb #ec9e1454
@delegates(_htmx_call)
async def find(selector, **kwargs):
    "Find first element matching `selector`; returns dict with id, tagName, outerHTML"
    return await _htmx_call('find', selector, **kwargs)

@delegates(_htmx_call)
async def findAll(selector, **kwargs):
    "Find all elements matching `selector`; returns dict with count and list of {id, tagName, outerHTML}"
    return await _htmx_call('findAll', selector, **kwargs)

@delegates(_htmx_call)
async def closest(elt, selector, **kwargs):
    "Find closest ancestor of `elt` matching `selector`; returns dict with id, tagName, outerHTML"
    return await _htmx_call('closest', elt, selector, **kwargs)

# %% ../nbs/00_htmx_bridge.ipynb #fed5034d
@delegates(_htmx_call)
async def remove(elt, delay=None, **kwargs):
    "Remove `elt` from the DOM, optionally after `delay` ms"
    return await _htmx_call('remove', elt, delay, **kwargs)

# %% ../nbs/00_htmx_bridge.ipynb #b2d8b324
@delegates(_htmx_call)
async def addClass(elt, cls, delay=None, **kwargs):
    "Add CSS `cls` to `elt`, optionally after `delay` ms"
    return await _htmx_call('addClass', elt, cls, delay, **kwargs)

@delegates(_htmx_call)
async def removeClass(elt, cls, delay=None, **kwargs):
    "Remove CSS `cls` from `elt`, optionally after `delay` ms"
    return await _htmx_call('removeClass', elt, cls, delay, **kwargs)

@delegates(_htmx_call)
async def toggleClass(elt, cls, **kwargs):
    "Toggle CSS `cls` on `elt`"
    return await _htmx_call('toggleClass', elt, cls, **kwargs)

@delegates(_htmx_call)
async def takeClass(elt, cls, **kwargs):
    "Take CSS `cls` from `elt`'s siblings so only `elt` has it"
    return await _htmx_call('takeClass', elt, cls, **kwargs)

# %% ../nbs/00_htmx_bridge.ipynb #6da2956c
@delegates(_htmx_call)
async def trigger(elt, name, detail=None, **kwargs):
    "Trigger browser event `name` on `elt` with optional `detail` payload"
    return await _htmx_call('trigger', elt, name, detail or {}, **kwargs)

@delegates(_htmx_call)
async def process(elt, **kwargs):
    "Process `elt` and its children, activating any htmx attributes"
    return await _htmx_call('process', elt, **kwargs)

# %% ../nbs/00_htmx_bridge.ipynb #ca8ce911
@delegates(_htmx_call)
async def values(elt, requestType='post', **kwargs):
    "Return input values htmx would submit for `elt` with `requestType`"
    return await _htmx_call('values', elt, requestType, **kwargs)

@delegates(_htmx_call)
async def parseInterval(s, **kwargs):
    "Parse an htmx interval string (e.g. '500ms', '2s') into milliseconds"
    return await _htmx_call('parseInterval', s, **kwargs)

@delegates(_htmx_call)
async def logAll(**kwargs):
    "Enable htmx event logging to console (useful for debugging)"
    return await _htmx_call('logAll', **kwargs)

@delegates(_htmx_call)
async def logNone(**kwargs):
    "Disable htmx event logging"
    return await _htmx_call('logNone', **kwargs)

# %% ../nbs/00_htmx_bridge.ipynb #48df1e1e
def _find_app_in_ns(port=8000):
    "Scan IPython user_ns for a JupyUvi instance on `port`"
    import IPython
    ns = IPython.get_ipython().user_ns
    for v in ns.values():
        if isinstance(v, JupyUvi) and v.port == port and v.server and v.server.started:
            return v.app
    return None

# %% ../nbs/00_htmx_bridge.ipynb #4871d0e3
def _make_endpoint(response):
    "Wrap a str/FT/callable as a Starlette async endpoint"
    async def endpoint(request):
        result = (await response(request)) if asyncio.iscoroutinefunction(response) else \
                 (response(request) if callable(response) else response)
        if not isinstance(result, str): result = to_xml(result)
        return HTMLResponse(result)
    return endpoint

# %% ../nbs/00_htmx_bridge.ipynb #31ae7dab
@delegates(_htmx_call)
async def ajax(verb, path, context=None, response=None, port=8000, **kwargs):
    "Issue an htmx-style AJAX request; if `response` given, serve it locally on `port`"
    if response is None: return await _htmx_call('ajax', verb, path, context if context is not None else {}, **kwargs)
    # local server mode
    tmp_path = f'/_tmp/{uuid4().hex}'
    route = Route(tmp_path, _make_endpoint(response), methods=['GET', 'POST'])
    server = None
    if not is_port_free(port):
        app = _find_app_in_ns(port)
        if app is None: raise RuntimeError(f"Port {port} in use but no JupyUvi app found in namespace")
    else:
        app, _ = fast_app()
        server = JupyUvi(app, port=port)
        # await asyncio.sleep(0.2)  # not needed? nb_serve blocks until server.started == True
    app.routes.insert(0, route)
    try: return await _htmx_call('ajax', verb, tmp_path, context if context is not None else {}, **kwargs)
    finally:
        app.routes.remove(route)
        if server: server.stop()
