"""Using `htmx` javascript API from python"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_htmx_bridge.ipynb.

# %% auto #0
__all__ = ['setup_htmx_bridge', 'js_eval', 'find', 'findAll', 'swap', 'trigger', 'process', 'trigger_ex', 'closest', 'remove',
           'addClass', 'removeClass', 'toggleClass', 'takeClass', 'values', 'parseInterval', 'logAll', 'logNone',
           'get_config', 'set_config', 'ajax', 'toggle_vars_sidebar', 'toggle_collapse', 'toggle_clamp', 'select_msg']

# %% ../nbs/01_htmx_bridge.ipynb #92031bb1
from importlib import resources
from uuid import uuid4
from fastcore.meta import delegates
from fastcore.xml import to_xml
from dialoghelper.core import iife_a, event_get_a, allow, read_msg, find_dname
from .server import local_server, wrap_endp

# %% ../nbs/01_htmx_bridge.ipynb #a78cb5ac
async def setup_htmx_bridge(debugger:bool=False):
    "Inject htmx bridge into the browser"
    txt = (resources.files('dutil')/'hx_bridge.js').read_text()
    await iife_a(f"{'debugger;\n' if debugger else ''}"+txt)

# %% ../nbs/01_htmx_bridge.ipynb #a5519ed7
async def _htmx_call(method, *args, port=8000, full_response=False, timeout=10, _retry=True):
    "Low-level async call to htmx JS API"
    res = await event_get_a('hx_bridge', timeout=timeout, data=dict(method=method, args=args, port=port, full_response=full_response))
    try: del res['data_id']
    except Exception:
        if _retry:
            await setup_htmx_bridge()
            return await _htmx_call(method, *args, port=port, full_response=full_response, timeout=timeout, _retry=False)
    return res

# %% ../nbs/01_htmx_bridge.ipynb #3043d5fe
@delegates(_htmx_call)
async def js_eval(expr, timeout=2, **kwargs):
    "Evaluate a JS expression in the browser and return the result"
    return await _htmx_call('eval', expr, timeout=timeout, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #c262b2db
@delegates(_htmx_call)
async def find(selector, root=None, **kwargs):
    "Find an element matching selector, optionally within root"
    return await _htmx_call('find', *([root, selector] if root else [selector]), **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #75e1fcd0
@delegates(_htmx_call)
async def findAll(selector, root=None, **kwargs):
    "Find all elements matching `selector`, optionally within `root`"
    return await _htmx_call('findAll', *([root, selector] if root else [selector]), **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #e8007759
@delegates(_htmx_call)
async def swap(target, content, swapSpec=None, swapOptions=None, **kwargs):
    "Perform an htmx swap, blocking until complete"
    if not isinstance(content, str): content = to_xml(content)
    spec = dict(swapStyle='innerHTML', scroll=False, show=False) | (swapSpec or {})
    return await _htmx_call('swap', target, content, spec, swapOptions or {}, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #9d683f70
@delegates(_htmx_call)
async def trigger(elt, name, detail=None, **kwargs):
    "Trigger browser event `name` on `elt` with optional `detail` payload"
    return await _htmx_call('trigger', elt, name, detail or {}, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #27fd62f5
@delegates(_htmx_call)
async def process(elt, **kwargs):
    "Process `elt` and its children, activating any htmx attributes"
    return await _htmx_call('process', elt, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #2c8a0ed3
@delegates(_htmx_call)
async def trigger_ex(elt, name, detail=None, wait_for='htmx:afterRequest', **kwargs):
    "Trigger browser event `name` on `elt`, blocking until `wait_for` event(s) fire or an error occurs"
    return await _htmx_call('trigger_ex', elt, name, detail or {}, wait_for, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #db1ed530
@delegates(_htmx_call)
async def closest(elt, selector, **kwargs):
    "Find closest ancestor of `elt` matching `selector`; returns dict with id, tagName, outerHTML"
    return await _htmx_call('closest', elt, selector, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #c0dbbab5
allow('find', 'findall', 'closest')

# %% ../nbs/01_htmx_bridge.ipynb #456f6e98
@delegates(_htmx_call)
async def remove(elt, delay=None, **kwargs):
    "Remove `elt` from the DOM, optionally after `delay` ms"
    return await _htmx_call('remove', elt, delay, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #f135c03a
@delegates(_htmx_call)
async def addClass(elt, cls, delay=None, **kwargs):
    "Add CSS `cls` to `elt`, optionally after `delay` ms"
    return await _htmx_call('addClass', elt, cls, delay, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #c8c150c4
@delegates(_htmx_call)
async def removeClass(elt, cls, delay=None, **kwargs):
    "Remove CSS `cls` from `elt`, optionally after `delay` ms"
    return await _htmx_call('removeClass', elt, cls, delay, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #435ab70a
@delegates(_htmx_call)
async def toggleClass(elt, cls, **kwargs):
    "Toggle CSS `cls` on `elt`"
    return await _htmx_call('toggleClass', elt, cls, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #2dcf31aa
@delegates(_htmx_call)
async def takeClass(elt, cls, **kwargs):
    "Take CSS `cls` from `elt`'s siblings so only `elt` has it"
    return await _htmx_call('takeClass', elt, cls, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #aa717713
@delegates(_htmx_call)
async def values(elt, requestType='post', **kwargs):
    "Return input values htmx would submit for `elt` with `requestType`"
    return await _htmx_call('values', elt, requestType, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #314f3f95
@delegates(_htmx_call)
async def parseInterval(s, **kwargs):
    "Parse an htmx interval string (e.g. '500ms', '2s') into milliseconds"
    return await _htmx_call('parseInterval', s, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #b4896c85
@delegates(_htmx_call)
async def logAll(**kwargs):
    "Enable htmx event logging to console (useful for debugging)"
    return await _htmx_call('logAll', **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #bffdd6eb
@delegates(_htmx_call)
async def logNone(**kwargs):
    "Disable htmx event logging"
    return await _htmx_call('logNone', **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #69df3757
@delegates(_htmx_call)
async def get_config(key, **kwargs):
    "Get an htmx config property by name"
    return await _htmx_call('get_config', key, **kwargs)

@delegates(_htmx_call)
async def set_config(key, value, **kwargs):
    "Set an htmx config property by name"
    return await _htmx_call('set_config', key, value, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #129167f4
@delegates(_htmx_call)
async def ajax(verb, path, context=None, response=None, port=8000, **kwargs):
    "Issue an htmx-style AJAX request; if `response` given, serve it locally on `port`"
    if response is None: return await _htmx_call('ajax', verb, path, context, port=port, **kwargs)
    base, _, qs = path.strip('/').partition('?')
    tmp_path = f"/_tmp_{uuid4().hex}{'/'+base if base else ''}"
    tmp_full = f"{tmp_path}?{qs}" if qs else tmp_path
    async with local_server(port=port) as srv:
        app = srv.app
        app.route(tmp_path, methods=['GET','POST','PUT','PATCH','DELETE'])(wrap_endp(response))
        route = [r for r in app.routes if r.path == tmp_path][0]
        app.routes.remove(route); app.routes.insert(0, route)
        try: return await _htmx_call('ajax', verb, tmp_full, context, True, port=port, **kwargs)
        finally: app.routes.remove(route)

# %% ../nbs/01_htmx_bridge.ipynb #41a976b8
async def toggle_vars_sidebar():
    sel = 'button[hx-get="/vars_sidebar_?oob="]'  # vars sidebar
    await trigger(sel, 'click')

# %% ../nbs/01_htmx_bridge.ipynb #ec4903f2
async def toggle_collapse(id:str=None):
    msgid = id or (await read_msg(0)).id
    sel = f'#{msgid} button[hx-post="/collapse_"]'
    await trigger(sel, 'click')

# %% ../nbs/01_htmx_bridge.ipynb #78e5494d
async def toggle_clamp(ids:str=None, inp:bool=True, dname:str=None):
    id = list(map(str.strip, ids.split(',')))[0] if ids else (await read_msg(0)).id
    dname = dname or find_dname().strip('/')
    d = {"values": {"is_input": int(inp), "dlg_name": dname, "id_": id, "ids": ids or id}, "swap": "none"}
    await ajax('POST', '/clamp_', d, full_response=True)

# %% ../nbs/01_htmx_bridge.ipynb #843a392b
async def select_msg(id:str=None):
    id = id or (await read_msg(0)).id
    await js_eval("selectMsg($('#%s'),{centered: true})" % id)
