"""Using `htmx` javascript API from python"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_htmx_bridge.ipynb.

# %% auto #0
__all__ = ['setup_htmx_bridge', 'HTMX', 'get_hx', 'toggle_vars_sidebar', 'toggle_collapse', 'toggle_clamp', 'select_msg']

# %% ../nbs/01_htmx_bridge.ipynb #92031bb1
from importlib import resources
from uuid import uuid4
from fastcore.foundation import AttrDict as AD, patch
from fastcore.meta import delegates
from fastcore.xml import to_xml
from dialoghelper.core import iife_a, event_get_a, allow, read_msg, find_dname
from .server import local_server, wrap_endp

# %% ../nbs/01_htmx_bridge.ipynb #a78cb5ac
_loaded = False
async def setup_htmx_bridge(debugger:bool=False):
    "Inject htmx bridge into the browser"
    global _loaded
    txt = (resources.files('dutil')/'hx_bridge.js').read_text()
    await iife_a(f"{'debugger;\n' if debugger else ''}"+txt)
    _loaded = True

# %% ../nbs/01_htmx_bridge.ipynb #a6d400ce
class HTMX:
    "A proxy for the htmx JS API"
    async def __call__(self, method, *args, full_response=False, timeout=10, _retry=True):
        "Low-level async call to htmx JS API"
        msgid = (await read_msg()).id
        res = await event_get_a('hx_bridge', timeout=timeout, data=dict(method=method, args=args, full_response=full_response, msgid=msgid))
        try: del res['data_id']
        except KeyError: pass
        if res is None:
            if not _loaded and _retry:
                await setup_htmx_bridge()
                return await self(method, *args, full_response=full_response, timeout=timeout, _retry=False)
            return AD(error=f"htmx bridge returned no response for '{method}'")
        return res if full_response else res.success if 'success' in res else res

# %% ../nbs/01_htmx_bridge.ipynb #11f944c7
__hx_ = None
def get_hx():
    global __hx_
    if __hx_ is None: __hx_ = HTMX()
    return __hx_

# %% ../nbs/01_htmx_bridge.ipynb #3043d5fe
@patch
@delegates(HTMX.__call__)
async def eval(self: HTMX, expr, timeout=2, **kwargs):
    "Evaluate a JS expression in the browser and return the result"
    return await self('eval', expr, timeout=timeout, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #17796b33
@patch
async def config(self:HTMX, k, v=None):
    "Get or set an htmx config property"
    res = await self('get_config', k) if v is None else await self('set_config', k, v)
    return res.value if hasattr(res, 'value') else res

# %% ../nbs/01_htmx_bridge.ipynb #c262b2db
@patch
@delegates(HTMX.__call__)
async def find(self:HTMX, selector, root=None, **kwargs):
    "Find an element matching selector, optionally within root"
    return await self('find', *([root, selector] if root else [selector]), **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #75e1fcd0
@patch
@delegates(HTMX.__call__)
async def findAll(self:HTMX, selector, root=None, **kwargs):
    "Find all elements matching `selector`, optionally within `root`"
    return await self('findAll', *([root, selector] if root else [selector]), **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #e8007759
@patch
@delegates(HTMX.__call__)
async def swap(self:HTMX, target, content, swapSpec=None, swapOptions=None, **kwargs):
    "Perform an htmx swap, blocking until complete"
    if not isinstance(content, str): content = to_xml(content)
    spec = dict(swapStyle='innerHTML', scroll=False, show=False) | (swapSpec or {})
    return await self('swap', target, content, spec, swapOptions or {}, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #9d683f70
@patch
@delegates(HTMX.__call__)
async def trigger(self:HTMX, elt, name, detail=None, **kwargs):
    "Trigger browser event `name` on `elt` with optional `detail` payload"
    return await self('trigger', elt, name, detail or {}, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #27fd62f5
@patch
@delegates(HTMX.__call__)
async def process(self:HTMX, elt, **kwargs):
    "Process `elt` and its children, activating any htmx attributes"
    return await self('process', elt, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #2c8a0ed3
@patch
@delegates(HTMX.__call__)
async def trigger_ex(self:HTMX, elt, name, detail=None, wait_for='htmx:afterRequest', **kwargs):
    "Trigger browser event `name` on `elt`, blocking until `wait_for` event(s) fire or an error occurs"
    return await self('trigger_ex', elt, name, detail or {}, wait_for, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #db1ed530
@patch
@delegates(HTMX.__call__)
async def closest(self:HTMX, elt, selector, **kwargs):
    "Find closest ancestor of `elt` matching `selector`; returns dict with id, tagName, outerHTML"
    return await self('closest', elt, selector, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #c0dbbab5
allow('find', 'findall', 'closest')

# %% ../nbs/01_htmx_bridge.ipynb #456f6e98
@patch
@delegates(HTMX.__call__)
async def remove(self:HTMX, elt, delay=None, **kwargs):
    "Remove `elt` from the DOM, optionally after `delay` ms"
    return await self('remove', elt, delay, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #f135c03a
@patch
@delegates(HTMX.__call__)
async def addClass(self:HTMX, elt, cls, delay=None, **kwargs):
    "Add CSS `cls` to `elt`, optionally after `delay` ms"
    return await self('addClass', elt, cls, delay, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #c8c150c4
@patch
@delegates(HTMX.__call__)
async def removeClass(self:HTMX, elt, cls, delay=None, **kwargs):
    "Remove CSS `cls` from `elt`, optionally after `delay` ms"
    return await self('removeClass', elt, cls, delay, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #435ab70a
@patch
@delegates(HTMX.__call__)
async def toggleClass(self:HTMX, elt, cls, **kwargs):
    "Toggle CSS `cls` on `elt`"
    return await self('toggleClass', elt, cls, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #2dcf31aa
@patch
@delegates(HTMX.__call__)
async def takeClass(self:HTMX, elt, cls, **kwargs):
    "Take CSS `cls` from `elt`'s siblings so only `elt` has it"
    return await self('takeClass', elt, cls, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #aa717713
@patch
@delegates(HTMX.__call__)
async def values(self:HTMX, elt, requestType='post', **kwargs):
    "Return input values htmx would submit for `elt` with `requestType`"
    return await self('values', elt, requestType, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #314f3f95
@patch
@delegates(HTMX.__call__)
async def parseInterval(self:HTMX, s, **kwargs):
    "Parse an htmx interval string (e.g. '500ms', '2s') into milliseconds"
    return await self('parseInterval', s, **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #b4896c85
@patch
@delegates(HTMX.__call__)
async def logAll(self:HTMX, **kwargs):
    "Enable htmx event logging to console (useful for debugging)"
    return await self('logAll', **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #bffdd6eb
@patch
@delegates(HTMX.__call__)
async def logNone(self:HTMX, **kwargs):
    "Disable htmx event logging"
    return await self('logNone', **kwargs)

# %% ../nbs/01_htmx_bridge.ipynb #129167f4
@patch
@delegates(HTMX.__call__)
async def ajax(self:HTMX, verb, path, context=None, response=None, port=8000, **kwargs):
    "Issue an htmx-style AJAX request; if `response` given, serve it locally on `port`"
    if response is None: return await self('ajax', verb, path, context, **kwargs)
    base, _, qs = path.strip('/').partition('?')
    tmp_path = f"/_tmp_{uuid4().hex}{'/'+base if base else ''}"
    tmp_full = f"{tmp_path}?{qs}" if qs else tmp_path
    async with local_server(port=port) as srv:
        app = srv.app
        app.route(tmp_path, methods=['GET','POST','PUT','PATCH','DELETE'])(wrap_endp(response))
        route = [r for r in app.routes if r.path == tmp_path][0]
        app.routes.remove(route); app.routes.insert(0, route)
        try: return await self('ajax', verb, tmp_full, context, True, **kwargs)
        finally: app.routes.remove(route)

# %% ../nbs/01_htmx_bridge.ipynb #41a976b8
async def toggle_vars_sidebar():
    sel = 'button[hx-get="/vars_sidebar_?oob="]'  # vars sidebar
    await get_hx().trigger(sel, 'click')

# %% ../nbs/01_htmx_bridge.ipynb #ec4903f2
async def toggle_collapse(id:str=None):
    msgid = id or (await read_msg(0)).id
    sel = f'#{msgid} button[hx-post="/collapse_"]'
    await get_hx().trigger(sel, 'click')

# %% ../nbs/01_htmx_bridge.ipynb #78e5494d
async def toggle_clamp(ids:str=None, inp:bool=True, dname:str=None):
    id = list(map(str.strip, ids.split(',')))[0] if ids else (await read_msg(0)).id
    dname = dname or find_dname().strip('/')
    d = {"values": {"is_input": int(inp), "dlg_name": dname, "id_": id, "ids": ids or id}, "swap": "none"}
    await get_hx().ajax('POST', '/clamp_', d, full_response=True)

# %% ../nbs/01_htmx_bridge.ipynb #843a392b
async def select_msg(id:str=None):
    id = id or (await read_msg(0)).id
    await get_hx().eval("selectMsg($('#%s'),{centered: true})" % id)
