"""simple logger using idiomatic Solveit"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_logger.ipynb.

# %% auto #0
__all__ = ['Logger']

# %% ../nbs/01_logger.ipynb #38e6b396
from datetime import datetime
from dialoghelper.core import update_msg, add_msg, del_msg

# %% ../nbs/01_logger.ipynb #bc9d711d
class Logger:
    logs:list
    msgid:str
    _s:str=''
    def __init__(self, id:str|None=''): self.logs = []; self.setup(id)
    def setup(self, id:str='', clear:bool=False): 
        self.msgid = id or (None if id is None else add_msg('' if clear else self._s, msg_type='raw'))
        if clear: self.clear()
    def clear(self): 
        self.logs.clear(); self._s=''; 
        update_msg(self.msgid, content='')
    def show(self, clear:bool=False):
        if not self.msgid: return
        del_msg(self.msgid)
        self.setup('', clear)
    def __call__(self, msg, *args, **kwargs): 
        s = f"[{datetime.now():%H:%M:%S}] {msg}"
        self.logs.insert(0, s)
        if self.msgid:
            self._s = f"{s}  \n" + self._s
            update_msg(self.msgid, content=self._s)
        else: print(s, flush=True)

