"""simple logger using idiomatic Solveit"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_logger.ipynb.

# %% auto #0
__all__ = ['Logger', 'findlogtarget']

# %% ../nbs/01_logger.ipynb #38e6b396
import time
from fastcore.all import patch
from datetime import datetime
from dialoghelper.core import update_msg, add_msg, del_msg, read_msg, find_msg_id

# %% ../nbs/01_logger.ipynb #bc9d711d
class Logger:
    logs:list
    msgid:str
    _s:str=''
    def __init__(self, id:str|None=''): self.logs = []; self.setup(id)
    def setup(self, id:str='', clear:bool=False): 
        self.msgid = id or (None if id is None else add_msg('' if clear else self._s, msg_type='raw'))
        if clear: self.clear()
    def clear(self): 
        self.logs.clear(); self._s=''; 
        update_msg(self.msgid, content='')
    def __call__(self, msg, *args, **kwargs): 
        s = f"[{datetime.now():%H:%M:%S}] {msg}"
        self.logs.insert(0, s)
        if self.msgid:
            self._s = f"\u200b{s}\n" + self._s
            update_msg(self.msgid, content=self._s)
        else: print(s, flush=True)


# %% ../nbs/01_logger.ipynb #9064e8e0
_notfound = {'msg': {}}
def findlogtarget(id:str=''):
    if (msg := read_msg(0, True, id) if id else read_msg(1, True)) == _notfound: return ''
    return msg.id if (cnt := msg.content).count('\n') == cnt.count('\u200b')-1 else ''

@patch
def show(self:Logger, clear:bool=False, replace:bool=False):
    if not self.msgid: return
    del_msg(self.msgid)
    self.setup(find_msg_id() if replace else findlogtarget(), clear)
    time.sleep(0.2)
    if self.msgid: update_msg(id=self.msgid, msg_type='raw', content=self._s)
