"""simple logger using idiomatic Solveit"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_logger.ipynb.

# %% auto #0
__all__ = ['findlogtarget', 'Logger']

# %% ../nbs/01_logger.ipynb #38e6b396
import time
from fastcore.all import patch
from datetime import datetime
from anyio import sleep
from anyio.from_thread import start_blocking_portal
from dialoghelper.core import update_msg, add_msg, del_msg, read_msg, find_msg_id, msg_idx, find_dname

# %% ../nbs/01_logger.ipynb #2ff25c6f
_notfound = {'msg': {}}
def findlogtarget(id:str='', n:int=1):
    if (msg := read_msg(0, id=id) if id else read_msg(n)) == _notfound: return ''
    return msg.id if (cnt := msg.content).count('\n') == cnt.count('\u200b')-1 else ''

# %% ../nbs/01_logger.ipynb #bc9d711d
class Logger:
    logs:list; msgid:str; _s:str
    def __init__(self, id:str|None=''): self.logs = []; self._s='\u200b'; self.setup(id, True)
    def setup(self, id:str|None='', clear:bool=False): 
        self.msgid = id
        if id is not None:
            if id and isinstance(msg_idx(id), int):  # reuse given target
                if not clear: update_msg(self.msgid, msg_type='raw')
            elif id := findlogtarget():  # reuse or create a new target
                self.msgid = id
                if clear: self.clear()
            else: self.msgid = add_msg('\u200b' if clear else self._s, msg_type='raw'); clear = False
        if clear: self.clear()
    def clear(self): 
        self.logs.clear(); self._s='\u200b'; 
        if self.msgid: update_msg(self.msgid, content=self._s, msg_type='raw')
    def settle(self, to:float=2.0, interval:float=0.1):
        if logid := self.msgid:
            dname, thisloc = find_dname(), msg_idx()  # capture dname, find_dname is not threadsafe
            async def _wait():
                t0 = time.time()
                while time.time()-t0 < to and msg_idx(logid, dname=dname) != thisloc: await sleep(interval)
                return msg_idx(logid, dname=dname) == thisloc
            with start_blocking_portal() as portal: return portal.call(_wait)
    def __call__(self, msg, *args, **kwargs): 
        dt = datetime.now()
        s = f"[{dt:%H:%M:%S}.{dt.microsecond//1000:03d}] {msg}"
        self.logs.insert(0, s)
        if self.msgid:
            self._s = f"\u200b{s}\n" + (self._s if self._s != '\u200b' else '')
            update_msg(self.msgid, content=self._s)
        else: print(s, flush=True)


# %% ../nbs/01_logger.ipynb #23b4e5ca
@patch
def show(self:Logger, clear:bool=False, replace:bool=False):
    if not self.msgid: return
    if  (loc := msg_idx(self.msgid)) and msg_idx() == loc-1: return
    oldid = self.msgid
    self.setup(find_msg_id() if replace else findlogtarget(), clear)
    if oldid != self.msgid: del_msg(oldid)
    time.sleep(0.1)
    self.settle()
    if self.msgid and not clear: update_msg(id=self.msgid, content=self._s)
