# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dlgutil',
                'doc_host': 'https://civvic.github.io',
                'git_url': 'https://github.com/civvic/dlgutil',
                'lib_path': 'dlgutil'},
  'syms': {'dlgutil.core': {'dlgutil.core.foo': ('core.html#foo', 'dlgutil/core.py')}}}
